name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ctse-assignment3-product-microservice:latest
          
#     - uses: actions-hub/kubectl@master
#       env:
#           KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#       with:
#           args: get pods

    - uses: azure/k8s-set-context@v2
      with:
          method: kubeconfig
          kubeconfig:  ${{ secrets.KUBE_CONFIG }}
          context: ${{ secrets.KUBE_CONTEXT }} 
    
    - name: Print current working dir
      run: |
         ls -la $PWD
         ls -la $GITHUB_WORKSPACE
          
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1
      with:        
        manifests: |
          ${{ github.workspace }}/kubernetes-configs/product-api-deployment.yaml
          ${{ github.workspace }}/kubernetes-configs/product-api-service.yaml
